apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tor-controller
spec:
  releaseName: tor-controller
  chart:
    spec:
      chart: tor-controller
      version: 0.1.4
      sourceRef:
        kind: HelmRepository
        name: bugfest
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    # Default values for tor-controller.
    # This is a YAML-formatted file.
    # Declare variables to be passed into your templates.

    # -- Daemonset replica count
    replicaCount: 1

    # -- tor-controller image, it watches onionservices objects
    image:
      repository: quay.io/bugfest/tor-controller
      pullPolicy: Always
      # -- Overrides the image tag whose default is the chart appVersion.
      tag: ""

    manager:
      # -- tor-controller-manager image, it runs Tor client
      image:
        repository: quay.io/bugfest/tor-daemon-manager
        pullPolicy: Always
        # -- Overrides the image tag whose default is the chart appVersion.
        tag: ""

    onionbalance:
      # -- tor-controller-manager image, it runs Tor client
      image:
        repository: quay.io/bugfest/tor-onionbalance-manager
        pullPolicy: Always
        # -- Overrides the image tag whose default is the chart appVersion.
        tag: ""

    imagePullSecrets: []
    nameOverride: ""
    fullnameOverride: ""

    serviceAccount:
      # -- Specifies whether a service account should be created
      create: true
      # -- Annotations to add to the service account
      annotations: {}
      # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
      name: "tor-controller-sa"

    podAnnotations: {}

    podSecurityContext:
      runAsNonRoot: true
      # fsGroup: 2000

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000

    service:
      type: ClusterIP
      port: 8443

    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi

    nodeSelector:
      doks.digitalocean.com/node-pool: josa-cloud-np

    tolerations: []

    affinity: {}
