apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whoami-prod
  namespace: whoami
spec:
  releaseName: whoami-prod
  chart:
    spec:
      chart: whoami
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: josa-charts
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt"
        external-dns.alpha.kubernetes.io/target: nginx.ingress.cloud.josa.ngo
        external-dns.alpha.kubernetes.io/ingress-hostname-source: defined-hosts-only
        start.josa.ngo/type: application
        start.josa.ngo/name: "Whoami"
        start.josa.ngo/url: "https://whoami.xpand.josa.ngo"
        start.josa.ngo/icon: "check-network"
      hosts:
        - host: whoami.xpand.josa.ngo
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - whoami.xpand.josa.ngo
          secretName: whoami-prod-tls
      resources:
        limits:
          cpu: 100m
          memory: 50Mi
        requests:
          cpu: 100m
          memory: 10Mi
