apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  labels:
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/name: authelia
    argocd.argoproj.io/instance: authelia
  name: authelia-auth
spec:
  forwardAuth:
    address: http://authelia.iam.svc.cluster.local/api/verify?rd=https%3A%2F%2Fid.josa.ngo%2F
    authResponseHeaders:
      - Remote-User
      - Remote-Name
      - Remote-Email
      - Remote-Groups
