apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: security-headers
spec:
  #Headers
  headers:
    customFrameOptionsValue: SAMEORIGIN
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    contentSecurityPolicy: upgrade-insecure-requests
    hostsProxyHeaders: [X-Forwarded-For]
    #HSTS
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 15552000
